### ISSUE TITLE
Allow setting UID/GID of user

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/ansible-role-omero-web#6]
see:

 * https://github.com/openmicroscopy/ansible-role-omero-web/blob/master/tasks/web-user.yml#L4
 * https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=8397&start=10#p18793

Depending on what workflows we want to enable for developers, being able to define the UID for `omero-web` may be valuable.

**Comment by manics** [comment]
What changes are required that can't be handled by `docker run --user UID`?

**Comment by joshmoore** [comment]
That doesn't change the UID/GID of the files owned by that user,  right? The goal in that thread is to be able to access the source file to develop on omero-web. The `docker cp` workflow there would need this change. Other ideas welcome.

**Comment by manics** [comment]
https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=8397&start=10#p18793
![forum-image](https://user-images.githubusercontent.com/1644105/33066206-9843548e-cea2-11e7-86e9-2225ed5bb986.png)

A host directory is being mount on `/opt/omero/web`, which means the permissions and UID should be entirely determined by the host system.

**Comment by joshmoore** [comment]
I don't follow. The goal of using `docker cp` was to have a simple way to get the valid values out for editing. However, `docker cp` transforms permissions even when using `-a`. Another option would be to have all of `/opt/omero/web` in a volume, but that's not currently the case. The downstream dockerfile that I added on that forum post does the trick, but it's suboptimal.

**Comment by manics** [comment]
If the primary goal is development I'd have though it'd be easier to download OMERO.py on the host, mount that on `/opt/omero/web/OMERO.web`, run the docker container with your local UID, and make changes on your host, bypassing the need to copy files back and forth.

**Comment by joshmoore** [comment]
> what would be even nicer is if you could git clone https://github.com/openmicroscopy/openmicroscopy locally and mount a subdir of that on /opt/omero/web/OMERO.web

Not exactly the same, but at least for the OMERO.server image there's now https://github.com/openmicroscopy/openmicroscopy/pull/5656/files#diff-3254677a7917c6c01f55212f86c57fbf
